# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import skills_pb2 as skills__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in skills_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SkillServiceStub(object):
    """══════════════════════════════════════════════════════════════════════════
    Servicio principal: SkillService
    ══════════════════════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/sarai.skills.SkillService/Infer',
                request_serializer=skills__pb2.InferRequest.SerializeToString,
                response_deserializer=skills__pb2.InferResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/sarai.skills.SkillService/Check',
                request_serializer=skills__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=skills__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/sarai.skills.SkillService/GetMetrics',
                request_serializer=skills__pb2.MetricsRequest.SerializeToString,
                response_deserializer=skills__pb2.MetricsResponse.FromString,
                _registered_method=True)


class SkillServiceServicer(object):
    """══════════════════════════════════════════════════════════════════════════
    Servicio principal: SkillService
    ══════════════════════════════════════════════════════════════════════════

    """

    def Infer(self, request, context):
        """Inferencia síncrona (request/response)
        CRÍTICO: debe completar en <30s (timeout del host)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Health check (integración con grpc.health.v1.Health)
        Usado por Docker HEALTHCHECK y k8s probes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Métricas Prometheus (opcional, para observabilidad avanzada)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkillServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=skills__pb2.InferRequest.FromString,
                    response_serializer=skills__pb2.InferResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=skills__pb2.HealthCheckRequest.FromString,
                    response_serializer=skills__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=skills__pb2.MetricsRequest.FromString,
                    response_serializer=skills__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sarai.skills.SkillService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sarai.skills.SkillService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SkillService(object):
    """══════════════════════════════════════════════════════════════════════════
    Servicio principal: SkillService
    ══════════════════════════════════════════════════════════════════════════

    """

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sarai.skills.SkillService/Infer',
            skills__pb2.InferRequest.SerializeToString,
            skills__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sarai.skills.SkillService/Check',
            skills__pb2.HealthCheckRequest.SerializeToString,
            skills__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sarai.skills.SkillService/GetMetrics',
            skills__pb2.MetricsRequest.SerializeToString,
            skills__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
